basePath: /v1
definitions:
  models.CreateUser:
    properties:
      f_name:
        type: string
      l_name:
        type: string
      monthly:
        type: string
      password:
        type: string
      position:
        type: string
    type: object
  models.Get:
    properties:
      created_at:
        type: string
      deleted_at:
        type: string
      f_name:
        type: string
      hours:
        $ref: '#/definitions/models.Hour'
      id:
        type: string
      l_name:
        type: string
      monthly:
        type: string
      password:
        type: string
      position:
        type: string
      updated_at:
        type: string
    type: object
  models.GetUser:
    properties:
      id:
        type: string
      password:
        type: string
    type: object
  models.Hour:
    properties:
      Opened:
        type: string
      closed:
        type: string
      daily:
        type: string
      id:
        type: string
      last_name:
        type: string
      monthly:
        type: string
      user_id:
        type: string
    type: object
  models.UpReq:
    properties:
      f_name:
        type: string
      l_name:
        type: string
      new_password:
        type: string
      old_password:
        type: string
      position:
        type: string
    type: object
  models.User:
    properties:
      created_at:
        type: string
      deleted_at:
        type: string
      f_name:
        type: string
      id:
        type: string
      l_name:
        type: string
      monthly:
        type: string
      password:
        type: string
      position:
        type: string
      updated_at:
        type: string
    type: object
info:
  contact: {}
  title: Task api
paths:
  /user:
    post:
      consumes:
      - application/json
      description: Get My Profile
      parameters:
      - description: Password
        in: path
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      security:
      - BearerAuth: []
      summary: Login
      tags:
      - User
  /user/{id}:
    delete:
      consumes:
      - application/json
      description: Delete User
      parameters:
      - description: Password
        in: path
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
      security:
      - BearerAuth: []
      summary: DeleteUser
      tags:
      - User
    get:
      consumes:
      - application/json
      description: Get User
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.GetUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Get'
      security:
      - BearerAuth: []
      summary: GetUser
      tags:
      - User
    put:
      consumes:
      - application/json
      description: Update User
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.UpReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      security:
      - BearerAuth: []
      summary: Update User
      tags:
      - User
  /users:
    post:
      consumes:
      - application/json
      description: This API for creating a new user
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.CreateUser'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.User'
      summary: Create new user
      tags:
      - User
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
